### ISSUE TITLE
Implementare selezione laboratori da lista

### ISSUE THREAD

**Issue by macteo** [route-nazionale/app-scanner#4]

**Comment by cortinico** [comment]
Intendi questo? Perche' nel caso e' gia' una listview. Purtroppo non avendo i dati sui capispalla si prova male.

![Immagine](http://s8.postimg.org/s41aels45/device_2014_07_24_153117.png)

**Comment by macteo** [comment]
Si, magari se avanza tempo si può prevedere una casella di ricerca per codice e titolo.

**Comment by cortinico** [comment]
Si, il fatto e' che li appare la lista, per ogni turno, degli eventi per cui sei stato inserito come capospalla. E' significativo fare una ricerca?

**Comment by macteo** [comment]
Pensavo apparissero tutti, se sono già filtrati non serve di sicuro.
