### ISSUE TITLE
Crash scansionando il QR su G+

### ISSUE THREAD

**Issue by porelli** [route-nazionale/app-scanner#6]
1) Login con ID: OT-1541-028230-0
2) Scegliere "identifica"
3) Scansionare il QR presente sulla pagina G+ "http://chart.apis.google.com/chart?chs=300x300&cht=qr&chld=%7C1&chl=AG-0943-006139-0"

Crash :(

Nota, con altri QR che non c'entrano nulla con la route il programma non crasha ma ovviamente non mi fornisce i dati relativi al badge.

**Comment by cortinico** [comment]
Che versione dell'app hai (la vedi in alto a destra sullo splash screen)

**Comment by porelli** [comment]
0.2

**Comment by cortinico** [comment]
Prova a scansionare questi 2:

http://chart.apis.google.com/chart?chs=300x300&cht=qr&chld=%7C1&chl=AG-0943-006139-0

http://chart.apis.google.com/chart?chs=300x300&cht=qr&chld=%7C1&chl=

Dovrebbe andare con il primo e crashare con il secondo giusto?

**Comment by porelli** [comment]
Confermo il comportamento previsto

primo OK
secondo KO

**Comment by cortinico** [comment]
Ok fixo in giornata

**Comment by cortinico** [comment]
Stasera pubblico una nuova versione sullo store con implementato 51ec52d che corregge il bug

**Comment by cortinico** [comment]
Bug corretto nella versione v.0.2.2 che sara' a breve online sul Play Store

**Comment by porelli** [comment]
Confermo il corretto funzionamento anche sul mio terminale, grazie
