### ISSUE TITLE
Login riuscito con data di nascita errata

### ISSUE THREAD

**Issue by porelli** [route-nazionale/app-scanner#7]
1) Inserire come nome utente "AG-0395-018827-0" oppure "OT-1541-028230-0"
2) Inserire una data di nascita a caso

L'autenticazione avverà sempre con successo

**Comment by macteo** [comment]
Questa è grave. Puoi verificare subito Nicola?

**Comment by cortinico** [comment]
No purtroppo dipende da @cuginolancio e' lui che gestisce il lato web delle autenticazioni.

Per generare 2 utenze di test ci sta che sia stato messo un controllo brutale della serie 
if codice = uno dei due allora autenticaz.
Non tenendo conto della data di nascita. Confermi @cuginolancio?
